language: clojure

before_install:
    - yes | sudo lein upgrade

before_script:
    - lein cljsbuild once

script:
    - lein test :yes-i-know-the-tests-are-supposed-to-fail | diff test/fixtures/test_output -
    - lein cljsbuild test 2>&1 | diff test/fixtures/test_output_cljs -

